### ISSUE TITLE
Suggestion: Add a method for purging the entire cache to `IdentityManager`

### ISSUE THREAD

**Issue by MrMage** [sprocketbox/eloquence#2]
Reasoning: Sometimes I might have performed a bunch of bulk changes and want to ensure that all data is reloaded "fresh" from the database. In such cases, a "nuclear" option for purging the cache might be helpful.

**Comment by ollieread** [comment]
Good call @MrMage. Will look into it.

**Comment by ollieread** [comment]
This has now been addressed and released as v1.1.0
